Проект "Седона": разметка
htmlacademy-htmlcss/2050153-sedona-34 pull request #2
Opened 2022-05-26 05:06 UTC by NataliZin85

2022-05-26 09:46 UTC, amaringo requested changes

2022-05-26 09:46 UTC, amaringo commented on index.html
> +        <ul class="navigahion-menu-list">
🟡 Нужно пройтись автозаменой по файлу, заменить все "navigahion" на "navigation"

2022-05-26 09:46 UTC, amaringo commented on index.html
> +            <a class="navigation-menu-link navigation-menu-link-curent" href="index.html">Главная</a>
🟡 "current"

2022-05-26 09:46 UTC, amaringo commented on index.html
> +              </span>
🟡 Нужен ещё один спан для количества пунктов в избранном. И у него должен быть свой класс, чтобы потом найти его через js

2022-05-26 09:46 UTC, amaringo commented on index.html
> +        <h1 class="visually-hidden">Добро пожаловать на сайт о Сидоне</h1>
🟡 "Седоне"

2022-05-26 09:46 UTC, amaringo commented on index.html
> +        <img class="vector" src="" alt="Sedona-because the grand canyon sucks">
🟡 Всё от "welcome" до "sucks" можно будет экспортировать одной картинкой, оставь один img, и заверни его в div, чтобы потом сделать ему фон с каньоном.

2022-05-26 09:46 UTC, amaringo commented on index.html
> +        <img class="background-image" src="">
🔴 Фоновые картинки указываются потом в стилях, не в разметке.

2022-05-26 09:46 UTC, amaringo commented on index.html
> +        <img class="background-image" src="" alt="divider">
🔴 Белые зубцы - декор, в разметку не надо его класть, потом сделаем фоном.

2022-05-26 09:46 UTC, amaringo commented on index.html
> +        <h4 class="hero-advantages">Рассмотрим 5 причин, по которым Седона круче, чем Гранд-Каньон!</h4>
🟡 Не заголовок, просто абзац.

2022-05-26 09:46 UTC, amaringo commented on index.html
> +        <ul class="advantages-1-list">
🟡 Цифры в классах использовать не принято, да и нет такой надобности, особенно тут. Просто удали все цифры. Для общих стилей на компоненты ставишь общий класс, если нужно их дополнить -добавляешь ещё один. Посмотри, как в навигации (13 строка) мы выделили кнопку текущей страницы.

2022-05-26 09:46 UTC, amaringo commented on index.html
> +            <h5 class="advantages-1-number">№1</h5>
🟡 Никакого резюмирования нижележащих элементов этот номер не выполняет, значит, это не заголовок. Просто спан.

2022-05-26 09:46 UTC, amaringo commented on index.html
> +            <h3 class="advantages-1-title">Настоящий <br> городок</h3>
🟡 Удали все `br` из разметки, сначала научимся без них работать. В большинстве случаев они не нужны.

2022-05-26 09:46 UTC, amaringo commented on index.html
> +            <img class="advantages-1-reasons-1" src="" alt="дом">
🔴 Эти три иконки - декор, удали, пожалуйста.

2022-05-26 09:46 UTC, amaringo commented on index.html
> +            <h3 class="advantages-1-reasons-title">жилье</h3>
🔴 Пункты "жилье/еда/сувениры" являются подпунктами первой причины про городок. Отрази это иерархией заголовков - смени эти на `h4`.

2022-05-26 09:46 UTC, amaringo commented on index.html
> +      <section class="advantages">
🟡 Стоит добавить скрытый заголовок с текстом навроде "Причины, по которым Седона круче"

2022-05-26 09:46 UTC, amaringo commented on index.html
> +        <h2 class="interested-title">Заинтересовались?</h2>
🟡 Не заголовок. Секция не про интерес, а про предложение заполнить форму бронирования. Отрази это в скрытом заголовке, а этот элемент можно сделать тегом `b`

2022-05-26 09:46 UTC, amaringo commented on index.html
> +        <h4 class="interested-instruction">Укажите предполагаемые даты поездки,<br>и мы покажем вам лучшие предложения гостиниц в Седоне</h4>
🟡 Не заголовок, параграф.

2022-05-26 09:46 UTC, amaringo commented on index.html
> +      <section class="subscribtion">
🟡 'subscription'

2022-05-26 09:46 UTC, amaringo commented on index.html
> +        <h4 class="subscription-instruction">Только полезная информация и никакого спама,<br>честное бойскаутское!</h4>
🟡 Не заголовок, параграф.

2022-05-26 09:46 UTC, amaringo commented on index.html
> +        <form class="subscription-form" action="#" method="post">
🟡 В описании задания есть адрес сервера Академии для проверки форм.

2022-05-26 09:46 UTC, amaringo commented on index.html
> +          <label for="subscription-email"></label>
🟡 Нужен текст лейбла. В макете его нет, так что добавь скрывающий класс

2022-05-26 09:46 UTC, amaringo commented on index.html
> +            <span class="visually-hidden">Подписаться</span>
🔴 Лишний спан, текст в атрибуте `value` должен нормально читаться скринридерами

2022-05-26 09:46 UTC, amaringo commented on index.html
> +      <section class="footer-social">
🔴 Секции нужны нам для крупных смысловых кусков сайта. В футер, хедер и друг в друга их вкладывать не нужно. Замени эти на div, в этом теге нет ничего плохого.

2022-05-26 09:46 UTC, amaringo commented on index.html
> +        <h2 class="visually-hidden">Социальные сети</h2>
🟡 Думаю, лишний заголовок. Лучше в  каждой ссылке на соцсеть подробнее написать что-то вроде "Ссылка на наш Ютуб"

2022-05-26 09:46 UTC, amaringo commented on index.html
> +          <li class="footer-social-item">
🟡 Добавить уникальный класс, ведь у соц.кнопок разные иконки

2022-05-26 09:46 UTC, amaringo commented on index.html
> +        <h2 class="visually-hidden">Звоните на</h2>
🟡 Не заголовок, можно просто `span`

2022-05-26 09:46 UTC, amaringo commented on index.html
> +          <div class="visually-hidden">.html-academy</div>
🟡 Для коротких подписей можно просто `span`

2022-05-26 09:46 UTC, amaringo commented on index.html
> +    <!-- <p>Репозиторий создан для обучения на профессиональном онлайн‑курсе «<a href="https://htmlacademy.ru/intensive/htmlcss">HTML и CSS. Профессиональная вёрстка сайтов</a>».</p> -->
🟡 Уже не нужен =)

2022-05-26 10:28 UTC, NataliZin85 commented on index.html
> +            <a class="navigation-menu-link navigation-menu-link-curent" href="index.html">Главная</a>
fixed

2022-05-26 10:28 UTC, NataliZin85 commented on index.html
> +              </span>
done

2022-05-26 10:30 UTC, NataliZin85 commented on index.html
> +        <h1 class="visually-hidden">Добро пожаловать на сайт о Сидоне</h1>
done

2022-05-26 10:34 UTC, NataliZin85 commented on index.html
> +        <img class="vector" src="" alt="Sedona-because the grand canyon sucks">
А что на счет, того что я вставила 'background-image? После этих строк с вектором...

2022-05-26 10:40 UTC, NataliZin85 commented on index.html
> +        <img class="background-image" src="" alt="divider">
Я не совсем поняла как это работает, вот и внесла их разметку. все убрала. Спасибо

2022-05-26 10:44 UTC, NataliZin85 commented on index.html
> +        <h4 class="hero-advantages">Рассмотрим 5 причин, по которым Седона круче, чем Гранд-Каньон!</h4>
fixed

2022-05-26 11:01 UTC, NataliZin85 commented on index.html
> +        <ul class="advantages-1-list">
done

2022-05-26 11:05 UTC, NataliZin85 commented on index.html
> +            <h5 class="advantages-1-number">№1</h5>
Немного не поняла, почему <span>. Поменяла

2022-05-26 11:08 UTC, NataliZin85 commented on index.html
> +            <h3 class="advantages-1-title">Настоящий <br> городок</h3>
ок, я думала-это надежнее... Поясни позже, пожалуйста.

2022-05-26 11:16 UTC, NataliZin85 commented on index.html
> +            <img class="advantages-1-reasons-1" src="" alt="дом">
done

2022-05-26 11:19 UTC, NataliZin85 commented on index.html
> +            <h3 class="advantages-1-reasons-title">жилье</h3>
done

2022-05-26 13:01 UTC, NataliZin85 commented on index.html
> +      <section class="advantages">
сделано

2022-05-26 13:08 UTC, NataliZin85 commented on index.html
> +        <h2 class="interested-title">Заинтересовались?</h2>
Не совсем поняла, что я должна отразить в скрытом заголовке

2022-05-26 13:12 UTC, NataliZin85 commented on index.html
> +        <h4 class="interested-instruction">Укажите предполагаемые даты поездки,<br>и мы покажем вам лучшие предложения гостиниц в Седоне</h4>
done

2022-05-26 13:12 UTC, NataliZin85 commented on index.html
> +      <section class="subscribtion">
done

2022-05-26 13:13 UTC, NataliZin85 commented on index.html
> +        <h4 class="subscription-instruction">Только полезная информация и никакого спама,<br>честное бойскаутское!</h4>
done

2022-05-26 13:18 UTC, NataliZin85 commented on index.html
> +        <form class="subscription-form" action="#" method="post">
done

2022-05-26 13:18 UTC, NataliZin85 commented on index.html
> +          <label for="subscription-email"></label>
done

2022-05-26 13:20 UTC, NataliZin85 commented on index.html
> +            <span class="visually-hidden">Подписаться</span>
done

2022-05-26 13:26 UTC, NataliZin85 commented on index.html
> +        <h2 class="visually-hidden">Социальные сети</h2>
не совсем согласна

2022-05-26 13:29 UTC, NataliZin85 commented on index.html
> +          <li class="footer-social-item">
done

2022-05-26 13:30 UTC, NataliZin85 commented on index.html
> +        <h2 class="visually-hidden">Звоните на</h2>
не совсем согласна

2022-05-26 13:32 UTC, NataliZin85 commented on index.html
> +    <!-- <p>Репозиторий создан для обучения на профессиональном онлайн‑курсе «<a href="https://htmlacademy.ru/intensive/htmlcss">HTML и CSS. Профессиональная вёрстка сайтов</a>».</p> -->
удалила

2022-05-26 15:58 UTC, amaringo requested changes

2022-05-26 15:58 UTC, amaringo commented on catalog.html
> +        <header class="inner-header">
🔴 Проблемы с отступами здесь и ниже. Нужно привести всё к одному виду - 2 отступа. Автоматическое выравнивание есть в редакторе, попробуй `Shift` + `Option` + `F`

2022-05-26 15:58 UTC, amaringo commented on catalog.html
> +        </header>
🔴 Можно положить этот хедер в секцию ниже, чтобы дать ей фоновую картинку как в макете. А результаты поиска с сортировкой положить в отдельный блок, отделив от формы поиска.

2022-05-26 15:58 UTC, amaringo commented on catalog.html
> +            <form class="catalog-filter" action="#" method="get"></form>
🔴 Лишний закрывающий тег, ниже есть ещё один. И надо будет поправить отступы вложенности у всего содержимого формы.

2022-05-26 15:58 UTC, amaringo commented on catalog.html
> +              <button class="button" type="submit">Применить</button>
🟡 Для удобства расположения по сетке можно дать этой паре кнопок обёртку, чтобы получилось три элемента в ряд.

2022-05-26 15:58 UTC, amaringo commented on catalog.html
> +                <ul class="product-view-user-list">
🟡 Список по умолчанию имеет display:block , как и div. Здесь ему не нужна обертка.

2022-05-26 15:58 UTC, amaringo commented on catalog.html
> +                      <a class="product-view-user-link" href="#">
🔴 Перехода на другую страницу нет, замени на кнопку.

2022-05-26 15:58 UTC, amaringo commented on catalog.html
> +            <div class="product-card">
🟡Несколько однотипных объектов мы оформляем в списки. Хорошо подойдёт для карточек гостиниц.

2022-05-26 15:58 UTC, amaringo commented on catalog.html
> +                <a class="product-card-link" href="#">
🟡 нигде нет информации, что фотографии должны быть ссылками, давай упростим.

2022-05-26 15:58 UTC, amaringo commented on catalog.html
> +                <ul class="product-card-description">
🟡Нет перечисления похожих элементов - список не нужен.

2022-05-26 15:58 UTC, amaringo commented on catalog.html
> +                    <li class="product-card-item">Гостиница</li>
🟡 Предлагаю поменять класс на более точный - "product-card-type"

2022-05-26 15:58 UTC, amaringo commented on catalog.html
> +                <ul class="navigation-product">
🟡 две похожих кнопки - ещё не список. Можно просто положить их рядом друг с другом

2022-05-26 15:58 UTC, amaringo commented on catalog.html
> +                        <button class="button-blue" type="submit" aria-checked="current">в избранное</и>
🔴 В макете другой текст. И цвет отличается, значит нужен дополнительный класс.

2022-05-26 15:58 UTC, amaringo commented on catalog.html
> +                <form class="product-card-description" action="#" method="get">
🔴 Не форма, просто тексты.

2022-05-26 15:58 UTC, amaringo commented on catalog.html
> +                    <a class="pagination-link pagination-disabled">...</a>
🟡Это не отключенная кнопка, а кнопка, чтобы показать ещё несколько кнопок страниц

2022-05-26 15:58 UTC, amaringo commented on catalog.html
> +            <p>Гостиниц на странице:</p>
🟡Это можно сделать лейблом селекта, и потом обернуть их в одну обёртку, чтобы считались одним элементом для внешней сетки. Они же бесполезны поодиночке.

2022-05-27 04:26 UTC, amaringo commented on index.html
> +        <img class="vector" src="" alt="Sedona-because the grand canyon sucks">
Все фоновые картинки ставятся через CSS? в разметке они не нужны.

2022-05-28 02:58 UTC, NataliZin85 commented on catalog.html
> +                <ul class="product-view-user-list">
не совсем поняла, нужно пояснение

2022-05-28 03:04 UTC, NataliZin85 commented on catalog.html
> +            <div class="product-card">
не поняла, нужно пояснение

2022-05-28 03:07 UTC, NataliZin85 commented on catalog.html
> +                <a class="product-card-link" href="#">
так нужно же делать с расчетом на развитие? оно по идее должно потом вести на страницу конкретной гостиницы... поясни пожалуйста

2022-05-28 03:09 UTC, NataliZin85 commented on catalog.html
> +                <ul class="product-card-description">
Я таким образом объединила этот небольшой блок... тогда как?

2022-05-28 03:14 UTC, NataliZin85 commented on catalog.html
> +                <ul class="navigation-product">
пояснение пожалуйста

2022-05-28 03:33 UTC, NataliZin85 commented on catalog.html
> +                    <a class="pagination-link pagination-disabled">...</a>
я не совсем поняла как это прописывать, поясните пожалуйста

2022-06-02 15:44 UTC, amaringo requested changes

2022-06-02 15:44 UTC, amaringo commented on index.html
> +        <h2 class="visually-hidden">Социальные сети</h2>
Ничего страшного, если оставишь.

2022-06-02 15:44 UTC, amaringo commented on index.html
> +        <h2 class="visually-hidden">Звоните на</h2>
Мне кажется чрезмерным подписывать каждый элемент футера, да ещё и заголовками. Хватило бы одного в начале футера - "Наши контактные данные"

2022-06-02 15:44 UTC, amaringo commented on index.html
> +        <h2 class="interested-title">Заинтересовались?</h2>
Описание содержимого секции. В секции есть кнопка вызова формы бронирования. Упомяни эту форму.

2022-06-02 15:44 UTC, amaringo commented on index.html
> +      <section class="subscribtion">
Не исправлено в каталоге

2022-06-02 15:44 UTC, amaringo commented on index.html
> +      <img class="logo" src="images/header-logo.svg" width="139" heigh="70" alt="Логотип Седона">
🔴 height - эту ошибку показывает валидатор на https://validator.w3.org/nu/#textarea , не забывай им проверять свою разметку

2022-06-02 15:44 UTC, amaringo commented on index.html
> +        <<h2 class="visually-hidden">Поиск гостиниц и форма заказа</h2>
🔴 лишняя '<', тоже ловится валидатором

2022-06-02 15:44 UTC, amaringo commented on index.html
> +        <p class="hero-advantages">Рассмотрим 5 причин, по которым Седона круче, чем Гранд-Каньон!</p>
🟡 Для этих двух параграфов тоже нужна обертка div, чтобы задать ей белый фон и декоративный элемент.

2022-06-02 15:44 UTC, amaringo commented on index.html
> +        <ul class="advantages-brige-list">
🟡 здесь и ниже - может, "bridge" ?)

2022-06-02 15:44 UTC, amaringo commented on index.html
> +          <label class="visually-hidden" for="subscription-email"></label>
🔴 Нужен текст в лейбле, например - "Введите свой email чтобы подписаться на рассылку"

2022-06-02 15:44 UTC, amaringo commented on index.html
> +          <div class="visually-hidden">.html-academy</div>
🟡 Не нужен, можно просто дополнить текст в alt логотипа, например - "Логотип разработчика - Htmlacademy"

2022-06-02 15:44 UTC, amaringo commented on catalog.html
> +    <img class="logo" src="images/header-logo.svg" width="139" heigh="70" alt="Логотип Седона">
🔴 ошибка валидации, неверное имя атрибута

2022-06-02 15:44 UTC, amaringo commented on catalog.html
> +            <input class="catalog-filter-price-range-field" type="number" name="product-price" value="от">
🔴 В числовом поле ввода нельзя писать буквы. Поменяй на 0 и 9000, как в макете. "От" и "До" - это лейблы этих инпутов. Пока просто положи их рядом с инпутами, свяжи атрибутом for

2022-06-02 15:44 UTC, amaringo commented on catalog.html
> +      <span class="product-search">
🔴 Ошибка валидации - в спан нельзя вкладывать "p", замени на div

2022-06-02 15:44 UTC, amaringo commented on catalog.html
> +          <a class="navigation-product-link" type="button" href="#">подробнее</a>
🔴 Ошибка валидации - у ссылок не бывает type="button"

2022-06-02 15:44 UTC, amaringo commented on catalog.html
> +            <a class="breadcrumbs-link">Гостиницы</a>
🟡 Не хватает href="#"

2022-06-02 15:44 UTC, amaringo commented on catalog.html
> +      <form class="catalog-filter" action="#" method="get">
🟡 Добавь адрес сервера Академии для проверки форм, как в форме подписки

2022-06-02 15:44 UTC, amaringo commented on catalog.html
> +      <div class="product-view">
🟡 div вокруг списка не нужен, я объяснял это на прошлом созвоне.

2022-06-02 15:44 UTC, amaringo commented on catalog.html
> +        <p>Гостиниц на странице:</p>
🔴 Это лейбл селекта ниже

2022-06-03 07:39 UTC, NataliZin85 commented on catalog.html
> +            <input class="catalog-filter-price-range-field" type="number" name="product-price" value="от">
надеюсь я правильно исправила

2022-06-05 04:13 UTC, merged