Базовая стилизация
htmlacademy-htmlcss/2050153-sedona-34 pull request #3
Opened 2022-06-08 02:15 UTC by NataliZin85

2022-06-08 13:49 UTC, amaringo requested changes

2022-06-08 13:49 UTC, amaringo commented on styles/styles.css
> +    src: url("../fonts/ptsans-400.woff2") format(woff2);
🔴 Шрифты не подключились, значение формата надо писать в кавычках - `format("woff2")`

2022-06-08 13:49 UTC, amaringo commented on styles/styles.css
> +    visibility: hidden;
🔴 Этот способ скрытия нам не подходит. Он и оставляет пустое место в сетке страницы, что помешает в дальнейшем, и скрывает из дерева доступности все помеченные этим классом элементы, читалки не увидят их. Используй последний длинный способ из главы учебника 1.13

2022-06-08 13:49 UTC, amaringo commented on styles/styles.css
> +.subscription-button {
🔴 не задано семейство шрифта, на странице тут сейчас Arial

2022-06-08 13:49 UTC, amaringo commented on styles/styles.css
> +    font-family: inherit;
🔴 Не задан размер шрифта , в макете 18px

2022-06-08 13:49 UTC, amaringo commented on styles/styles.css
> +    background-repeat: no-repeat;
🔴 Не заданы шрифтовые стили по макету

2022-06-08 13:49 UTC, amaringo commented on styles/styles.css
> +    border-radius: 4px;
🔴 Не задано семейство шрифта

2022-06-08 13:49 UTC, amaringo commented on catalog.html
> +            <button class="navigation-product-button navigation-product-button-chosen" type="submit">в избранное</button>
🔴 Текст не совпадает с макетом

2022-06-08 13:49 UTC, amaringo commented on catalog.html
> +          <select name="number-choice" id="number-page">
🔴 Не заданы шрифтовые стили.

2022-06-09 03:02 UTC, NataliZin85 commented on catalog.html
> +            <button class="navigation-product-button navigation-product-button-chosen" type="submit">в избранное</button>
не поняла ?

2022-06-09 03:49 UTC, merged