Сетки страниц на флексах
htmlacademy-htmlcss/2050153-sedona-34 pull request #4
Opened 2022-06-13 04:40 UTC by NataliZin85

2022-06-13 06:20 UTC, amaringo requested changes

2022-06-13 06:20 UTC, amaringo commented on index.html
> +            <span class="advantages-number">-№1-</span>
🔴 Лучше заменить дефисы на тире, в макете именно они.

2022-06-13 06:20 UTC, amaringo commented on styles/styles.css
>    text-transform: capitalize;
🔴 Не нужно бездумно копировать стили из Фигмы, у тебя и так в разметке весь текст этих элементов написан с заглавной буквы.

2022-06-13 06:20 UTC, amaringo commented on styles/styles.css
> +  width: 390px;
🔴 Какой-то ошибочный стиль. Не нужно задавать ширину, ссылки будут шириной со своё текстовое содержимое.

2022-06-13 06:20 UTC, amaringo commented on styles/styles.css
> +  width: 264px;
🟡 Не нужна жесткая ширина и тут. В следующем ДЗ настроишь тут флексбокс и дашь отступы некоторым элементам.

2022-06-13 06:20 UTC, amaringo commented on styles/styles.css
> +  height: 767px;
🔴 Ошибка. Жёстко указывать высоту почти никогда не нужно, кроме абсолютно спозиционированных элементов, которые никогда не изменят свой размер. Замени на min-height, это даст возможность блоку реагировать на переполнение содержимого длинным текстом, например. Блок увеличится, так как ты уже добавила паддингов больше этого числа.

2022-06-13 06:20 UTC, amaringo commented on styles/styles.css
> +  height: 767px;
А лучше удали высоту здесь, и добавь минимальную обоим прямым потомкам этого блока - `hero-background` и `hero-text`

2022-06-13 06:20 UTC, amaringo commented on styles/styles.css
> +  padding-bottom: 82px;
🟡 Не надо давать внутренние отступы элементу, чтобы его спозиционировать внутри родителя. Дай родителю `hero-background` флексбокс и отцентруй картинку с помощью него.

2022-06-13 06:20 UTC, amaringo commented on styles/styles.css
> +  height: 339px;
🔴 min-height

2022-06-13 06:20 UTC, amaringo commented on styles/styles.css
> +  background-image: url(../images/hero-divider.svg);
🔴 Это лучше сделать псевдоэлементом в домашнем задании про декоративные элементы. Сейчас убери фон, пожалуйста

2022-06-13 06:20 UTC, amaringo commented on styles/styles.css
> +  background-color: none;
🔴 В макете тут белый цвет. И у этого свойства не бывает значения `none`

2022-06-13 06:20 UTC, amaringo commented on styles/styles.css
> +  margin-top: -57px;
🔴 Отрицательный отступ используется в крайне редких случаях, когда нужно сделать наслоение блока на своего соседа. Но здесь такое городить точно не нужно, фигурный разделитель сделаешь абсолютно спозиционированным псевдоэлементом с свгшкой на фоне..

2022-06-13 06:20 UTC, amaringo commented on styles/styles.css
> +  padding: 0 273px;
🟡 Слишком большой паддинг по бокам - нижняя надпись не должна переноситься на вторую строку.

2022-06-13 06:20 UTC, amaringo commented on styles/styles.css
> +  height: 385px;
🔴 min-height

2022-06-13 06:20 UTC, amaringo commented on styles/styles.css
> +  height: 383px;
🔴 min-height

2022-06-13 06:20 UTC, amaringo commented on styles/styles.css
> +  padding: 103px 85px;
🟡 Нужно уменьшить отступы по бокам, параграфы слишком сжаты, перенос происходит раньше чем нужно. А вот заголовкам  нужно добавить своих отступов, сейчас некоторые в одну строку помещаются.

2022-06-13 06:20 UTC, amaringo commented on styles/styles.css
> +  height: 417px;
🔴 min-height

2022-06-13 06:20 UTC, amaringo commented on styles/styles.css
> +  height: 411px;
🔴 min-height

2022-06-13 06:20 UTC, amaringo commented on styles/styles.css
> +  height: 120px;
🔴 min-height

2022-06-13 06:20 UTC, amaringo commented on styles/styles.css
> +  width: 720px;
🟡 Не нужна тут ширина. Родитель уже флексбоксом отцентровал этот элемент. Пусть занимает столько, сколько его текст занимает. Уберёшь - ничего не изменится.

2022-06-13 06:20 UTC, amaringo commented on styles/styles.css
> +  width: 115px;
🟡 Не нужна тут явно указанная ширина, картинка в ссылке уже имеет такой размер.

2022-06-15 02:05 UTC, NataliZin85 commented on styles/styles.css
> +  width: 390px;
немного не поняла эту поправку. Я задала ширину этому блоку... поясни пожалуйста

2022-06-15 02:07 UTC, NataliZin85 commented on styles/styles.css
> +  width: 264px;
немного не поняла эту поправку. Я задала ширину этому блоку... поясни пожалуйста

2022-06-15 02:18 UTC, NataliZin85 commented on styles/styles.css
> +  height: 767px;
у бэкграунда уже задана высота. не знаю могу ли я ей задавать еще одну... Я сделала min-height для hero и hero-text. не уверенна, что это правильно. Я если честно просто баловалась с высотой, потом все сделаю правильно, по мере обучения.

2022-06-15 02:27 UTC, NataliZin85 commented on styles/styles.css
> +  background-image: url(../images/hero-divider.svg);
Я так долго думала куда же его вставить и придумала наверно не правильно. Но у меня получилось почти как в фигме :)

2022-06-15 02:33 UTC, NataliZin85 commented on styles/styles.css
> +  padding: 0 273px;
взяла из фигмы...

2022-06-16 01:17 UTC, amaringo requested changes

2022-06-16 01:17 UTC, amaringo commented on styles/styles.css
>  .hero-background {
Осталось дать высоту этому блоку, как в макете

2022-06-16 01:17 UTC, amaringo commented on styles/styles.css
> +  min-height: 339px;
В макете это 282 пикселя, декоративный элемент с зубцами не входит в размеры этого блока.

2022-06-16 01:17 UTC, amaringo commented on styles/styles.css
> +  min-height: 339px;
В макете это 282 пикселя, декоративный элемент с зубцами не входит в размеры этого блока.

2022-06-16 01:17 UTC, amaringo commented on styles/styles.css
> +  padding: 0 265px;
Почитай про отличия `box-sizing: border-box` и `box-sizing: content-box` [тут](http://simonenko.su/32197993404/use-css3-box-sizing) , после этого будет понятно, почему сейчас у тебя этот блок занимает 549 пикселей по высоте. Напоминаю, что критерий [CSS-02](https://up.htmlacademy.ru/htmlcss/34/criteries#CSS-02) разрешает дать всем элементам нужный box-sizing, если тебе так удобнее будет, посмотри примеры там

2022-06-16 01:17 UTC, amaringo commented on styles/styles.css
> +  padding: 0 265px;
Почитай про отличия `box-sizing: border-box` и `box-sizing: content-box` [тут](http://simonenko.su/32197993404/use-css3-box-sizing) , после этого будет понятно, почему сейчас у тебя этот блок занимает 549 пикселей по высоте. Напоминаю, что критерий [CSS-02](https://up.htmlacademy.ru/htmlcss/34/criteries#CSS-02) разрешает дать всем элементам нужный box-sizing, если тебе так удобнее будет, посмотри примеры там

2022-06-16 01:17 UTC, amaringo commented on styles/styles.css
>  .advantages-bridge-item {
Ширина и высота этих блоков не совпадает с макетом, и серых тоже. Можно вообще всем li в .advantages задать ширину в 400px, а минимальную высоту в 384, по макету.

2022-06-16 01:17 UTC, amaringo commented on styles/styles.css
>  .advantages-bridge-item {
Ширина этих блоков не совпадает с макетом. Можно вообще всем li в .advantages задать ширину в 400px

2022-06-16 01:17 UTC, amaringo commented on styles/styles.css
> +.catalog-footer {
Футер полностью одинаковый на обеих страницах. Зачем нужны два класса для него?)

2022-06-16 01:17 UTC, amaringo commented on styles/styles.css
> +.catalog-footer {
Футер полностью одинаковый на обеих страницах. Зачем нужны два класса для него?)

2022-06-16 01:17 UTC, amaringo commented on styles/styles.css
> +  height: 393px;
В макете 403 пикселя. И надо заменить на минимальную высоту

2022-06-16 01:17 UTC, amaringo commented on styles/styles.css
> +  height: 393px;
В макете 403 пикселя. И надо заменить на минимальную высоту

2022-06-16 01:17 UTC, amaringo commented on styles/styles.css
> +  margin: 0 71px;
Замени на внутренний отступ, у блока же нет четких границ, пусть занимает всю ширину.

2022-06-16 01:17 UTC, amaringo commented on styles/styles.css
> +  margin: 0 71px;
Замени на внутренний отступ, у блока же нет четких границ, пусть занимает всю ширину.

2022-06-16 01:17 UTC, amaringo commented on styles/styles.css
> +  width: 338px;
Ошибка, лучше убрать ширину. Текущее значение не даст нормально расположиться трёхзначному или четырёхзначному числу найденных гостиниц, например.

2022-06-16 01:17 UTC, amaringo commented on styles/styles.css
> +  width: 338px;
Ошибка, лучше убрать ширину. Текущее значение не даст нормально расположиться трёхзначному или четырёхзначному числу найденных гостиниц, например.

2022-06-16 01:17 UTC, amaringo commented on styles/styles.css
> +  margin-left: 190px;
Нужно заменить на auto. Ты же не знаешь, какой ширины будет предыдущий блок с числом.

2022-06-16 01:17 UTC, amaringo commented on styles/styles.css
> +  margin-left: 190px;
Нужно заменить на auto. Ты же не знаешь, какой ширины будет предыдущий блок с числом.

2022-06-16 05:54 UTC, NataliZin85 commented on styles/styles.css
>  .hero-background {
не поняла...

2022-06-16 05:54 UTC, NataliZin85 commented on styles/styles.css
>  .hero-background {
высота как в макете... а ширина задана wrapper

2022-06-16 12:01 UTC, NataliZin85 commented on styles/styles.css
> +  height: 393px;
в моем макете 393рх

2022-06-23 03:13 UTC, merged