6. Сетки компонентов на флексах
htmlacademy-htmlcss/2050153-sedona-34 pull request #5
Opened 2022-06-25 09:48 UTC by NataliZin85

2022-06-26 02:50 UTC, amaringo requested changes

2022-06-26 02:50 UTC, amaringo commented on index.html
>              <button class="navigation-user-button" type="button">Хочу сюда!</button>
У этой кнопки не должно быть border, судя по макету

2022-06-26 02:50 UTC, amaringo commented on styles/styles.css
> +  padding: 0 362px;
Заголовку этому не нужен паддинг. Он занимает только одну строку, находится по центру, потому что родитель применяет к нему `text-align: center;`

2022-06-26 02:50 UTC, amaringo commented on styles/styles.css
> +  padding: 5px 194px;
Этот паддинг ничего не меняет, и никак не пригодится.

2022-06-26 02:50 UTC, amaringo commented on styles/styles.css
> +  min-height: 384px;
Здесь и 2 раза выше добавлены одни и те же стили. Нужно переделать классы в разметке так, чтобы обойтись минимумом кода стилей. Подробнее обсудим в ЛС

2022-06-29 09:17 UTC, NataliZin85 commented on index.html
>              <button class="navigation-user-button" type="button">Хочу сюда!</button>
я не прописывала border...?

2022-06-29 15:25 UTC, amaringo requested changes

2022-06-29 15:25 UTC, amaringo commented on styles/styles.css
>    background: rgba(131, 179, 211, 0.2);
Этот стиль цвета фона можно перенести в .advantages-item, чтобы не повторяться.

2022-06-29 15:25 UTC, amaringo commented on styles/styles.css
> +  background: rgba(131, 179, 211, 0.12);
Этот стиль цвета фона можно перенести в .advantages-item

2022-06-29 15:25 UTC, amaringo commented on styles/styles.css
> +  text-align: center;
Этот стиль можно перенести в .advantages-item

2022-06-29 15:25 UTC, amaringo commented on styles/styles.css
> +  background: #82B3D3;
Лучше убрать цветной фон из списков, и дать его самим квадратным блокам

2022-06-29 15:25 UTC, amaringo commented on styles/styles.css
> +.advantages-list-with-image {
Старый селектор был лучше, не надо было удалять классы `.advantages-town-item`, 
`.advantages-bridge-item`

2022-06-29 15:25 UTC, amaringo commented on index.html
> +          <li class="advantages-item advantages-item-with-image">
Старый класс лучше. Новый говорит, что в этом `advantages-item` якобы есть картинка, но по факту её там нет, она в соседнем элементе находится.

2022-06-29 15:25 UTC, amaringo commented on styles/styles.css
> +.advantages-item-description {
Эти два класса не нужны, стили там такие же , как и у `.advantages-title` , `.advantages-description`

2022-06-29 15:25 UTC, amaringo commented on styles/styles.css
> +  padding: 0 90px 30px;
Минимум 110 пикселей по бокам заголовков, чтобы переносы стали как в макете

2022-06-29 15:25 UTC, amaringo commented on styles/styles.css
> +.advantages-description {
Нужно задать описаниям отступы по бокам, чтобы соответствовать макету

2022-06-30 05:08 UTC, NataliZin85 commented on styles/styles.css
>    background: rgba(131, 179, 211, 0.2);
не совсем поняла? это разные цвета...

2022-06-30 05:10 UTC, NataliZin85 commented on styles/styles.css
> +  background: rgba(131, 179, 211, 0.12);
так же не поняла, я не повторяю этот цвет ни где кроме advantages-list?

2022-06-30 05:15 UTC, NataliZin85 commented on styles/styles.css
> +  text-align: center;
когда я переношу, то ломается структура...

2022-06-30 05:17 UTC, NataliZin85 commented on styles/styles.css
> +  background: #82B3D3;
поясни пожалуйста. Что тогда измениться и на что это повлияет?

2022-06-30 05:22 UTC, NataliZin85 commented on styles/styles.css
> +.advantages-list-with-image {
Тогда зачем было просить меня его заменить?

2022-06-30 05:28 UTC, NataliZin85 commented on styles/styles.css
> +.advantages-item-description {
я им дала другие стили, потому что у них расположение другое...

2022-07-06 06:19 UTC, merged